apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gwf3g8glo-python
  janus-idp.io/tekton: gwf3g8glo-python
  backstage.io/kubernetes-id: gwf3g8glo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gwf3g8glo-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
