apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gwf3g8glo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gwf3g8glo-python 
  name: gwf3g8glo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gwf3g8glo-python 
